### ISSUE TITLE
Delete Accounts

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#10]
## Idea
Users might not want their account after a certain amount of time. If a user deletes their account, all of their user data should be deleted along with any data that they created. This means that any chats they participated in, any events they RSVP'd to, etc, will be deleted. 

## Todo
- [x] Deleting account deletes _all_ data
- [x] Endpoints
     - [x] Delete Account Endpoint (need to be logged in, and password is required)
- [x] Testing
     - [x] Delete Account Endpoint

**Comment by William-McGonagle** [comment]
Neil just finished the endpoint for this and I will get started on testing suite soon!!!

**Comment by William-McGonagle** [comment]
Finished off the testing- deleting accounts is all done!
