### ISSUE TITLE
Database Cleanup System 

### ISSUE THREAD

**Issue by MassiGy** [fairfield-programming/backend-server#109]
## Idea

Since, we've created the email verification system, and it appears to be working, we need to create a system that will delete all the user records in our database with the `email_confirmed` attribute set to `false` for the past 30 days or so !

Basically, we need to get rid of the user's accounts that did not confirmed their email addresses a while ago , because they are considered inactive.

**Why should we implement this system**
- Gain in Database Storage & Performance.
- Optimize our Audience by Selecting a Highly Active User Base.
- Push the Users to be Active.

_Let me know your thoughts guys, and feel free to suggest and discuss down below !_

Hope that is clear !
Massiles.

## Todo

- [x] Create a node module, where we can fetch our user records and see the creation date.
- [x] Create a deletion algorithm that will delete all the related data and activity to the outdated user records.
- [x] Wrap this module in an interval ( use the `setInterval` Time Api function ) 
- [x] Execute it & test it .

**Comment by William-McGonagle** [comment]
I think this sounds like a great idea- I like the idea of using the `setInterval` API, do you think that would lead to too much slowdown of the server?

**Comment by MassiGy** [comment]
Yeah I was worrying about that, but it wont !

**Let me explain why :**
- First, this system will execute once a month or so.
- Second, this system will not fetch a third party data base or API, it will only remove some records on the local data base.
- Third, the number of this records will decrease over time. 
- Fourth, this is built-in nodejs, and one of the advantages of using node is that it has a non blocking event loop which means that it can run multiple things at the same time.
- Fifth, this will be the first version, and we can always come back to it and optimize it, keep in mind that the first thing to do is to create an mvp ( minimal valuable product ).


That are my current thoughts on the subject.
_let me know what you think_

Thanks in advance !
Massiles.

**Comment by William-McGonagle** [comment]
Hey @MassiGy- 

This sounds great- I can't wait to see what you come up with!

Thanks,
William McGonagle

**Comment by MassiGy** [comment]
Hey @William-McGonagle,

Thanks for the feedback, and your thoughts on this one ! 

I will eventually start coding this system, in the up coming days.

Thanks again !
Massiles.

**Comment by supernova350** [comment]
Using `setInterval` for something like this is a terrible idea. If the process is restarted, all intervals will be cleared.

**Comment by MassiGy** [comment]
Hey @supernova350,

Thanks for contributing on this, I really appreciate it.

Yeah, your point of view is totally right, and I saw that you've suggested to use an npm package for the scheduling part of the system. I think that it will be a very good idea.

_Please feel free to suggest your idea, or directly by code._

Thanks again.
Massiles.

**Comment by MassiGy** [comment]
hey @William-McGonagle,

I think after merging my PR, you can close this one.

Massiles.
