### ISSUE TITLE
Architecture Refactor.

### ISSUE THREAD

**Issue by MassiGy** [fairfield-programming/backend-server#113]
## Idea 
As the project grows, more and more routes are added. As a consequence, we need a better system for the files architecture. Currently, the entry file for our app is `src/index.js`, and we import all our routes into it. This is what happens.

![Screenshot from 2022-03-23 16-36-58](https://user-images.githubusercontent.com/82173113/159737492-66f7c96b-152c-477f-ac29-49502025a772.png)

As you can see this is not what you would call dry code, which is not great.

**What to do ?**
I would says that separating the routes, the controllers and the `src/index.js` file will be the best architecture that we can implement to follow the MVC schema.

In the controllers folder, we will have sub-folders in which we are going to have files that are related to the same events, like `controllers/user/auth/loginController.js` and `controllers/user/auth/signupController.js`.

In the routes folder, we will have our api routes in which we are going to use the controllers. For example, in the `/routes/userRoutes.js` we are going to use all the files inside the `/controllers/user/` folder. For that, we will use the `express.Router()` object.

Finally, in the `src/index.js` file we are going to import the routes and use them, like this.

```js
// IMPORTS 
const userRoutes = require("./routes/userRoutes.js");

// MIDDELWARES
app.use("/user", userRoutes);
```

To see more, please refer to this [link](https://github.com/MassiGy/programmer_notes_webapp/tree/master).

**Why should we do that ?**
- This will give our code a better architecture, so as the new comers can understand much more quickly how our code is organized.
- This will make our code more maintainable, and more DRY.
- This will make our code easier to document, so to maintain and update.

## Todo
- [x] Go and look at the link above.
- [x] `cd /src/ && mkdir routes controllers `
- [x] `cd controllers && mkdir users events duck`
- [x] `cd ../routes && touch usersRoutes.js eventsRoutes.js duckRoutes.js`
- [x] Move the code to the appropriate files, and test this new architecture.

---
_I would love to hear your comments for this one, and please refer to me if something is wrong._

Thanks in advance.
Massiles.

**Comment by MassiGy** [comment]
hey @William-McGonagle,

I think after merging my PR, you can close this one.

Massiles.

**Comment by NeilChaudhari** [comment]
Sounds Good @MassiGy!
