### ISSUE TITLE
Email Confirmation Reminder.

### ISSUE THREAD

**Issue by MassiGy** [fairfield-programming/backend-server#115]
## Idea
Since, we've created the email verification system, and it appears to be working, we need to create a system that will remind the users to confirm their email addresses before our Database Cleanup System #109  delete their accounts.

Basically, we need to send a second email to the users with an email address that is not confirmed within the first 14 days of their registration. If they do not confirm it, within the next 14 days, our Database Cleanup System #109  will remove their account.

## Benefits
The whole point of this is to remind our users to confirm their email address so as they can access all our platform services. Basically, give them a better UX.

## Todo

- [x] Create a new node module.
- [x] Fetch the user record with `confirmed_email=false` and `createdAt=14_DAYS_AGO`.
- [x] Send to them a new email, like the one we sent to them when they signed up, but with a different token.
- [x] Wrap this feature in a `cron` schedule, and fire it up every 14 days or so.
- [x] Execute it & test it.

Hope that is clear, and please let me know if something is wrong.
Massiles.

**Comment by NeilChaudhari** [comment]
Thanks @MassiGy for all your hard work!

**Comment by MassiGy** [comment]
Hey @NeilChaudhari,

Thank you so much for your feedback, I really appreciate it.

Speaking of feedback, please evaluate my usage of git and github overall. The reason why I'am asking is that I stated contributing to test how was my communication ( written English ), also to get some real world experience.

Thanks again.
Massiles.

**Comment by NeilChaudhari** [comment]
Hey Massiles,

Your communication skills, compared to many Americans, is phenomenal. You eloquently describe the issues that are present, and how you plan to fix them. You write in a way that is easy to understand, and easy to respond to. We are so lucky to have you as a part of our team, and you have nothing to worry about regarding your communication skills.

Have a great weekend!
~ Neil Chaudhari

**Comment by MassiGy** [comment]
Hey @NeilChaudhari,

Thank you so much for the great feedback. It helps a lot.

Yeah, I really wanted to evaluate my communication skills and some other soft skills of mine, before searching for a real position in the industry. So now , from your comment, I can be sure that is on point.

Thanks a lot.
Massiles.
