### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#12]
## Idea
Users may have leaked their password online or just need to change it for a number of different reasons. There needs to be some endpoints for changing the user's password. The user must also be logged in to use this endpoint or else it would defeat the purpose immensely. 

## Todo

- [x] Allow Users to Change Passwords
- [x] Users can only change passwords if logged in
- [x] Password cannot match existing password
- [x] Endpoints
     - [x] Set Password
- [x] Testing
     - [x] Set Password

**Comment by William-McGonagle** [comment]
Almost done- just need to do testing...

**Comment by William-McGonagle** [comment]
Finished it all up!
