### ISSUE TITLE
API Routes Design.

### ISSUE THREAD

**Issue by MassiGy** [fairfield-programming/backend-server#122]
## Current situation.

While refactoring the code, I've read the routes files a couple times, and I've clearly seen that the API Routes are not setup correctly. In other word, how our API behaves is not quiet good.

For example: 

---
![Screenshot from 2022-05-07 07-07-31](https://user-images.githubusercontent.com/82173113/167239379-09aae7ff-c6b5-4dbb-9ed3-e855a755488a.png)
---
As we can see in this one, we are using the same controller for the `GET` and the `POST` requests.

Also, we do not need the two `ids` in the `route`  to follow a user or unfollow one.  Since, the only user that can perform these tasks is the one that is currently using the platform, with that been said, this user will be always known by our server. So, is making his `id` on the `url` necessary ?. 

Same thing goes with the `/block/`  routes, regarding the `POST` requests.

---

![Screenshot from 2022-05-07 07-13-30](https://user-images.githubusercontent.com/82173113/167239505-cf4286e7-1987-442e-9df5-24f4d76552cd.png)

---

Finally, I think that designing great API routes is very important, since it keeps the development and the scalability of the platform easier to achieve, same thing regarding the security aspect.

## Todo

- [x] Design Better API Routes.
- [x] Adapt to this new Route signature.
- [x] Inform the front-end team, to update their API calls.

_Please refer to me if something is wrong._

Hope that is clear.
Massiles.

**Comment by MassiGy** [comment]
@William-McGonagle , @NeilChaudhari. I would love to hear your thoughts one this one as well.


Massiles.

**Comment by Lucky-victory** [comment]
The `id` param is unnecessary in the route since the user's `id` is gotten from the token gotten from **cookies**.
For the `block` route, the `get` method and the `post` method shouldn't be using the same `controller`, because the duty of the `get` route should be to fetch the list of blocked **users**, while the `post` should be to add a **user** to block list. 

I would love to work on this issue if you assign me.

**Comment by MassiGy** [comment]
Hey @Lucky-victory,

Yeah, that is what I discovered when refactoring the code.

Sure, you can start enrolling in it, and show us what design you can come up with.

I will be there to only review the code ( I think ) , since I am a little  busy these days.


Thanks in advance.
Massiles.

**Comment by MassiGy** [comment]
Hey @Lucky-victory, hope that you are doing well.

I think that these errors are local, cuz all the modals and `sequelize` instance itself are implicitly imported since they were added up to the node `global` object. ( Look up to the `/modals/index.js` file ).

That been said, I wonder if node is properly setup in your system, and if it is, try the `npm start` script to run the code, hoping that this will clear out the errors.

Another thing that can be done is to reinstall the dependencies, or run the `npm audit && npm fund && npm audit fix`   to fix all the `node_modules` related errors.


Hope that these little tips would help you, if not search for it.
Massiles.

**Comment by MassiGy** [comment]
Hey @Lucky-victory,

Well, exporting it or appending it to the global object are kind of the same thing at the end of the day.

If those bugs persist, just create a side `branch` and export it on your end.

That been said, I wonder if the suggestions that I gave you worked or not ?. 

Hope that is clear.
Massiles.

**Comment by Lucky-victory** [comment]
Alright, I will do the exporting on my end.

About if your tips helped, well, I Instantiated `Sequelize` so I was able to start the server.

**Comment by MassiGy** [comment]
Hey there, 

I've fixed this one on the PR #127. Let me know your thoughts.

Massiles.

**Comment by Lucky-victory** [comment]
Oh! That's great,
I haven't touched the routes, I have been working on the typings and exporting the Models instead of setting them to `global`

**Comment by MassiGy** [comment]
Yeah, great. But, that is just to get rid of your local bugs, so do not spend too much time on it.

Massiles.

**Comment by Lucky-victory** [comment]
I'm currently done with it
