### ISSUE TITLE
On Account Created, Automatically Set First and Last Name

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#126]
## Idea

Since we are adding first and last names to the database, we need initial values for them. To do this, we can infer the first and last names by splitting the username by the dash and then capitalizing the first letters of each word. The first name should just be the first word, and the last name should be the rest of the stuff. 

Leave a comment if you want to work on this or need help. 

Cheers!

## Todo

- [x] On Account Create, split username and capitalize the first letters of each word
- [x] The first word should be the first name.
- [x] All following words should be last names.
