### ISSUE TITLE
Build Auth Middleware

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#15]
## Idea
I need to build the middleware for the authorization. Pretty much there will be a bearer token in the authentication header and that will be the JWT token. This will then be checked to make sure that the user has the correct authorization. 

## Todo
- [x] Read the Auth Token
- [x] Set the `Req.Auth` token to false if not signed in
- [x] Set the `Req.Auth` token to be the user data if they are signed in

**Comment by William-McGonagle** [comment]
Finished the Middleware!
