### ISSUE TITLE
User System

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#2]
## Idea
The user system needs to be robust and yet simple. The main features behind it will be the biographies, status, and profile pictures. The profile picture system was already completed, so to finish it off, all I will need to do is link it using URLs. Then, I need to add a biography system, and I might want to force users to not use bad language (so I may have to build a new library for that). And then finally, the statuses will require their own endpoint because they are more 'real-time' than the other endpoints. 

## Todo
- [X] Create a List of Vulgar Words
- [x] Build Vulgar Detection Library
- [x] Force Authentication on all Endpoints
- [x] Endpoints
     - [x] Set Status
     - [x] Get Status
     - [x] Set Account Data
     - [x] Get Account
- [x] Testing
     - [x] Set Status
     - [x] Get Status
     - [x] Set Account Data
     - [x] Get Account

**Comment by William-McGonagle** [comment]
I finished the querying endpoints and the testing behind them, but I still need to add the setting user data endpoints.

**Comment by William-McGonagle** [comment]
I've also been thinking I should add an api-feature like the one that GitHub has where users can query:

```http
/user/8.png
```

And get redirected to the profile picture of that user.

**Comment by William-McGonagle** [comment]
Finished the Testing!!!
