### ISSUE TITLE
Revamp Duck Generator System to Allow for Direct Import of SVG

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#36]
## Idea
Currently, the duck system is a little stupid. I designed it so that it would work well with a low number of items, but I have started to realize that people want more and more things to choose from. That is why I have to rebuild the duck system from the ground up. 

1. To do this, I need to first create a new storage format for the duck information, that will be pretty easy, I just need to figure out how it will look. Information about that will be in [this issue](https://github.com/fairfield-programming/backend-server/issues/38). 

2. From there, I need to build a parser to interpret the storage format. Information about how the parser is going to work will be in [this issue](https://github.com/fairfield-programming/backend-server/issues/39). 

3. After that, I want all of the duck items to be stored in a very simple way. For this, I am thinking maybe to do a server or just read from the file system directly. I am not quite sure yet, but information about that will be in [this issue](https://github.com/fairfield-programming/backend-server/issues/40). 

4. And finally, I need to build a system for generating the final duck SVG from the duck items (Todo 3) and the duck storage format (Todo 4). Information about the duck SVG generation system will be in [this issue](https://github.com/fairfield-programming/backend-server/issues/36). 

## Todo
- [ ] General
     - [ ] Build Basic SVG Parser
     - [x] Build Duck Format Parser
     - [ ] Build a System for Generating Duck SVG
     - [x] Figure Out How to Store the Duck Items
- [ ] Testing
     - [ ] SVG Library Testing
     - [ ] GET /duck
     - [ ] `GET /duck/:id`
     - [ ] `GET /duck/:id/:zoom`
- [ ] Endpoints
     - [ ] GET /duck
     - [ ] `GET /duck/:id`
     - [ ] `GET /duck/:id/:zoom`

**Comment by William-McGonagle** [comment]
I'm getting this working right now- it will be done soon.

**Comment by William-McGonagle** [comment]
Okay- I finished this system. It is done.
