### ISSUE TITLE
Create an Endpoint to Follow a User

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#48]
## Idea
_Full Idea Here - #45_

There are currently endpoints being worked on that let users see who someone is following and who they are followed by, but there needs to be an endpoint for following someone. 

The endpoint path will be `/user/:id/follow` and it will be accessible using a post request. It will need to require authentication to determine the user id, and it should properly handle all edge cases (user doesn't exist, not logged in, etc). 

## Todo
- [x] Auth Required for Endpoint
- [x] Endpoints
     - [x] `POST /user/:id/follow`
- [ ] Testing
     - [ ] `POST /user/:id/follow`

**Comment by NeilChaudhari** [comment]
Follow and Unfollow User endpoints finished

**Comment by William-McGonagle** [comment]
We can add a testing suite in later issues- the code is looking nice!
