### ISSUE TITLE
Add Documentation to Duck Generator Library

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#51]
## Idea
The duck generator is a really great system, but the only problem is that there is no documentation for it. All of the code for the file can be found inside of the [`src/routes/Duck/` folder](https://github.com/fairfield-programming/backend-server/tree/master/src/routes/Duck). This is where all of the code for generating ducks can be found, but it all needs to be documented so it can be easily understood for new members of the project. 

## Todo
- [ ] Add some information about how duck strings are stored
     - [ ] Show what hex numbers mean what
     - [ ] This issue has some information about that - #38
- [ ] duckGenerator.js
     - [ ] Document the `parseDuckString()` method
     - [ ] Document the `getItemString()` method
     - [ ] Document the `generateDuck()` method
