### ISSUE TITLE
Add Documentation to Vulgar Detector

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#52]
## Idea
The backend server is getting huge, but we do not have a ton of documentation. This is a huge problem because there are people that would like to work on the project but are not sure where to start or what our code does. 

One of the parts of our system that is relatively unknown is the vulgar detector. I had to build this system to check all of the biographies and posts, and it works quite well at the moment (that's beside the point). We need to add some basic documentation that describes how the vulgar detector works and how to use it. 

You can find the code for the vulgar detector [here](https://github.com/fairfield-programming/backend-server/tree/master/src/library), and it should be readable. If you would like to do this, comment below, and I'll assign you to the issue. 

## Todo
- [ ] Document the `GetVulgarWords()` method
- [ ] Document the `TokenizeString()` method
- [ ] Document the `DetectVulgarWords()` method
