### ISSUE TITLE
RSVP System

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#7]
## Idea
The RSVP system should allow users to subscribe to events. This subscription will say that a user is going to go to a certain event. The user should not be able to subscribe to the event if they are not eligible to (I.E, the event is for delegates but the user isn't one). The users will then be notified of any changes to the event or anything that the event hosts would like the users to know. 

## Todo
- [x] Allow Users to Subscribe to an Event
- [x] Block Users from Subscribing if not Eligible
- [x] Add Email Alerts for the Event
- [x] Allow Users to Unsubscribe from an Event

**Comment by MassiGy** [comment]
Hey @William-McGonagle , @NeilChaudhari ,

I will try to setup the email alerts for the events. 

Massiles.

**Comment by MassiGy** [comment]
Hey @William-McGonagle , @NeilChaudhari.

As I said, I've been coding the email alerts for the events. My idea is to remind all the subscribers if an event to which they are subscribed to will take place soon.

In other words, if an event will take place in a day, then send an email notification to all the subscribers.

Now I have the job setup, I wrapped it up in a cron schedule, and I am able to execute it and get an email notification into my inbox.

Here is the resault. ( the quality of the image is not that good due to the out-zoom :/ ) .
---

![Screenshot from 2022-05-04 11-20-09](https://user-images.githubusercontent.com/82173113/166655604-a84db3ba-b8c4-4914-ac7f-6d1ccba8a557.png)

---

I will fire up a new PR soon for this code.

**Although**, as I keep reading the description, I think this is not the only event alert that we need. We also want to tell the subscribers if any changes had been made to one of the events to which they are subscribed to.

Please explain more deeply the second part of the request, a.k.a  _" or anything that the event hosts would like the users to know."_.

This will help us to understand what we need to develop.


Thanks in advance.
Massiles.

**Comment by MassiGy** [comment]
hey @William-McGonagle,

Could you explain more in depth how authorization will be setup for the users regarding the events. In other word, could you explain your thoughts when you've added ` Block Users from Subscribing if not Eligible` to the todos of this issue.

Thanks in advance.
Massiles.

**Comment by MassiGy** [comment]
The PR #133 fixes this one.

Massiles
