### ISSUE TITLE
Need Testing for Duck Jokes

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#9]
## About
I finished the whole duck joke system but I first off need to refactor it so that it supports indexing. And then secondly, I completely forgot to add a test suite for the jokes. 

I wish I could test if the duck puns were funny or not, but I'm pretty sure all of the tests would fail. 

## Todo 
- [x] Refactor Duck Joke System
     - [x] Build using File System
     - [x] Create a Central Lib File (similar to SVG duck system)
- [x] Add Endpoints
     - [x] To Get Joke Count
     - [x] To Get a Random Joke
     - [x] To Get Joke at Id
     - [x] To Get All Jokes as JSON Array
- [x] Add Tests
     - [x] To Get Joke Count
     - [x] To Get a Random Joke
     - [x] To Get Joke at Id
     - [x] To Get All Jokes as JSON Array

**Comment by William-McGonagle** [comment]
I just finished the central library and added the joke endpoints. I still need to create the tests though. (I know I should have done the tests first but I am too tired for test-driven development)

**Comment by William-McGonagle** [comment]
I just finished building all of the tests, and my code seems to be passing.
